Object.assign(details,{
'Gryffondor':'Le Choixpeau envoie Harry à Gryffondor après avoir entendu son souhait de ne pas aller à Serpentard.',
'Serdaigle':'La maison de Rowena Serdaigle valorise la connaissance, la sagesse et la vivacité d’esprit.',
'McGonagall':'Minerva McGonagall enseigne la métamorphose et peut elle-même se transformer en chat.',
'Flitwick':'Filius Flitwick enseigne les sortilèges et dirige la maison Serdaigle.',
'Pomona Chourave':'Les cours de botanique se déroulent dans les serres, où les élèves étudient les plantes magiques.',
'Argus Rusard':'Le concierge surveille les couloirs et traque les élèves qui enfreignent le règlement.',
'Miss Teigne':'La chatte de Rusard l’aide à repérer les élèves dans les couloirs.',
'Nick Quasi-Sans-Tête':'Le fantôme de Gryffondor doit son surnom à une décapitation incomplète.',
'Dans la Grande Salle':'Les quatre maisons y prennent leurs repas sous un plafond enchanté qui reproduit le ciel.',
'Madame Pomfresh':'L’infirmière soigne les nombreux accidents et blessures des élèves à Poudlard.',
'Madame Pince':'La bibliothécaire veille sur les livres et sur le silence de la bibliothèque.',
'La Forêt interdite':'Cette forêt abrite notamment des centaures et des acromentules. Les élèves ne doivent pas y entrer seuls.',
'Salazar Serpentard':'Salazar est l’un des quatre fondateurs de Poudlard et le créateur de la Chambre des secrets.',
'Pré-au-Lard':'Les élèves autorisés peuvent y visiter les boutiques et les Trois Balais.',
'Cuthbert Binns':'Le professeur poursuit ses cours d’histoire de la magie même après être devenu un fantôme.',
'Poufsouffle':'Cedric est élève de Poufsouffle et devient l’un des champions de Poudlard au Tournoi des Trois Sorciers.',
'Ron et Hermione':'Leur amitié se noue dès la première année et devient essentielle aux aventures de Harry.',
'Ginny':'Ginny est la plus jeune des enfants Weasley et la seule fille de la fratrie.',
'Lily':'Lily Potter protège Harry lorsque Voldemort attaque leur famille.',
'James':'James Potter est un Maraudeur, ami de Sirius, Remus et Peter.',
'Un chien':'Sirius est un Animagus et peut prendre la forme d’un grand chien noir.',
'Lovegood':'Luna Lovegood est élève de Serdaigle et devient une amie fidèle de Harry.',
'Fred et George':'Les jumeaux Weasley sont connus pour leurs farces et leur boutique de produits magiques.',
'Lucius Malefoy':'Lucius est le père de Drago et l’époux de Narcissa Malefoy.',
'9 ¾':'Les élèves accèdent au quai magique en traversant la barrière entre les quais 9 et 10.',
'Gringotts':'La banque du Chemin de Traverse est dirigée par des gobelins.',
'Ollivander':'Le fabricant de baguettes rappelle que c’est la baguette qui choisit son sorcier.',
'Azkaban':'Cette prison a longtemps été gardée par les Détraqueurs.',
"Une cape d'invisibilité":'Harry reçoit cette cape, autrefois possédée par son père, pendant sa première année.',
'Les personnes et passages de Poudlard':'La Carte du Maraudeur révèle les déplacements dans le château et plusieurs passages secrets.',
'La Bièraubeurre':'Les élèves apprécient cette boisson lors de leurs visites à Pré-au-Lard.'
});
